[build]
  publish = "_site"
  command = "npx eleventy && npx pagefind --source '_site'"

# Default
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 302

[[redirects]]
  from = "/*"
  to = "/fr/:splat"
  status = 302
  conditions = {Language = ["fr"]}